[profile.default]
src = 'contracts/LZV2'
out = 'out'
libs = ['node_modules', 'lib']
test = 'contracts/tests'
cache_path  = 'cache_forge'

solc_version='0.8.22'
evm_version='paris'
optimizer = true
optimizer_runs = 9999