[profile.default]
src = 'contracts/LZV2'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'

solc_version='0.8.22'
evm_version='paris'
optimizer = true
optimizer_runs = 9999


remappings = [
    "contracts/=contracts/LZV2/tOFT/",
    "contractsV1/=contracts/",
	'forge-deploy/=node_modules/forge-deploy/contracts/',
	"solidity-bytes-utils/=node_modules/@layerzerolabs/solidity-bytes-utils/"
]

# forge-dpeloy
fs_permissions = [
	{ access = "read-write", path = "./deployments"},
	{ access = "read", path = "./out"}
]

[etherscan]
arbitrum-sepolia = { key = "${ARBITRUM_SEPOLIA_API_KEY}", url = "https://api-sepolia.arbiscan.io/api"}